local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/TheMugenKingMods/Gui-Library/refs/heads/main/Gerad's"))()

local Window = Library:CreateWindow('ArceusXArchive') -- :CreateWindow(Title)

local Section = Window:Section('Feature') -- :Section(Title)

Section:Button('Lobby Win', function() -- :Button(Title, callback)
    local Players = game:GetService("Players")
local player = Players.LocalPlayer
local hrp = player.Character and player.Character:WaitForChild("HumanoidRootPart")

for i = 1, 5 do
    local winPart = workspace:FindFirstChild("Win" .. i)
    if winPart then
        local p = (winPart:IsA("BasePart") and winPart) or winPart:FindFirstChildWhichIsA("BasePart", true)
        if p then
            hrp.CFrame = p.CFrame
        end
    end
end
end)

Section:Button('Money', function() -- :Button(Title, callback)
    -- Generated by @TheMugenKing
local hrp = game:GetService('Players').LocalPlayer.Character:WaitForChild('HumanoidRootPart')
local SpawnList = {
    Vector3.new(743.17, 30.71, 130.41),
}
for _, pos in ipairs(SpawnList) do task.wait(0.4) hrp.CFrame = CFrame.new(pos) end
end)

Section:Button('Remove Door VIP', function() -- :Button(Title, callback)
    -- Hapus VipWall
local vipWall = workspace:FindFirstChild("VipWall")
if vipWall then
    vipWall:Destroy()
end

-- Hapus VIP
local vipMain = workspace:FindFirstChild("VIP")
if vipMain then
    vipMain:Destroy()
end
end)