local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/TheMugenKingMods/Gui-Library/refs/heads/main/Gerad's"))()

local Window = Library:CreateWindow('ArceusXArchive') -- :CreateWindow(Title)

local Section = Window:Section('Feature') -- :Section(Title)

Section:Button('Remove Door', function() -- :Button(Title, callback)
    local map = workspace:FindFirstChild("Map")
if map then
    -- Hapus GroupRewardWall
    local grw = map:FindFirstChild("GroupRewardWall")
    if grw then
        grw:Destroy()
    end

    -- Hapus Map.Tower.CodeDoor.Door
    local tower = map:FindFirstChild("Tower")
    if tower then
        local codeDoor = tower:FindFirstChild("CodeDoor")
        if codeDoor and codeDoor:FindFirstChild("Door") then
            codeDoor.Door:Destroy()
        end
    end
end
end)

Section:Button('Coli', function() -- :Button(Title, callback)
    -- Generated by @TheMugenKing
local hrp = game:GetService('Players').LocalPlayer.Character:WaitForChild('HumanoidRootPart')
local SpawnList = {
    Vector3.new(255.59, 99.00, 145.45),
}
for _, pos in ipairs(SpawnList) do task.wait(0.4) hrp.CFrame = CFrame.new(pos) end
end)

Section:Button('Money', function() -- :Button(Title, callback)
    local Players = game:GetService("Players")
local player = Players.LocalPlayer
local char = player.Character or player.CharacterAdded:Wait()
local hrp = char:WaitForChild("HumanoidRootPart")

local folder = workspace.Map.CoinGivers
for _, giver in pairs(folder:GetChildren()) do
    if giver:IsA("BasePart") then
        hrp.CFrame = giver.CFrame + Vector3.new(0, 3, 0)
        task.wait(0.2)
    else
        -- kalau model, cari part
        local p = giver:FindFirstChildWhichIsA("BasePart", true)
        if p then
            hrp.CFrame = p.CFrame + Vector3.new(0, 3, 0)
            task.wait(0.2)
        end
    end
end
end)

Section:Button('Coin', function() -- :Button(Title, callback)
    local hrp = game.Players.LocalPlayer.Character:WaitForChild("HumanoidRootPart")

for _, coin in ipairs(workspace.Map.Coins:GetChildren()) do
    if coin.Name == "Coin" and coin:IsA("BasePart") then
        hrp.CFrame = coin.CFrame
    end
end
end)