local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/TheMugenKingMods/Gui-Library/refs/heads/main/Gerad's"))()

local Window = Library:CreateWindow('ArceusXArchive') -- :CreateWindow(Title)

local Section = Window:Section('Feature') -- :Section(Title)

Section:Button('Remove Door VIP', function() -- :Button(Title, callback)
    -- Hapus VipWall
local vipWall = workspace:FindFirstChild("VipWall")
if vipWall then
    vipWall:Destroy()
end

-- Hapus VIP
local vipMain = workspace:FindFirstChild("VIP")
if vipMain then
    vipMain:Destroy()
end
end)

Section:Button('Money', function() -- :Button(Title, callback)
    -- Generated by @TheMugenKing
local hrp = game:GetService('Players').LocalPlayer.Character:WaitForChild('HumanoidRootPart')
local SpawnList = {
    Vector3.new(586.16, 30.71, 1327.71),
}
for _, pos in ipairs(SpawnList) do task.wait(0.4) hrp.CFrame = CFrame.new(pos) end
end)

Section:Button('Lobby Win', function() -- :Button(Title, callback)
    local Players = game:GetService("Players")
local player = Players.LocalPlayer
local char = player.Character or player.CharacterAdded:Wait()
local hrp = char:WaitForChild("HumanoidRootPart")

for i = 1, 5 do
    local winPart = workspace:FindFirstChild("Win" .. i)
    if winPart and winPart:IsA("BasePart") then
        hrp.CFrame = winPart.CFrame + Vector3.new(0, 3, 0)
        task.wait(0.2)
    elseif winPart then
        -- Kalau itu model, cari BasePart di dalamnya
        local part = winPart:FindFirstChildWhichIsA("BasePart", true)
        if part then
            hrp.CFrame = part.CFrame + Vector3.new(0, 3, 0)
            task.wait(0.2)
        end
    else
        warn("Win" .. i .. " tidak ditemukan")
    end
end
end)